#!/usr/bin/php

<?php
if (count($argv) != 2){
	$stderr = fopen('php://stderr', 'w');
	fwrite($stderr, "Usage: $argv[0] fichierdequiz \n");
	exit();	
}
chdir(dirname(__FILE__));
require_once('WhoWantsToBeAJedi.php');
echo json_encode (WhoWantsToBeAJedi::import('jedi/'.$argv[1]));
